name: cpblcalendar3
description: A CPBL Calendar port in Flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 4.3.0+2031

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Your other regular dependencies here
  json_annotation: ^4.0.1
  http: ^0.13.1

  # https://github.com/flutter/plugins
  shared_preferences: ^2.0.5
  package_info: ^2.0.0
  url_launcher: ^6.0.2
  # add dependency for Firebase Core
  firebase_core: ^1.0.2
  firebase_remote_config: ^0.9.0-dev
  #firebase_admob: ^0.11.0+2
  google_mobile_ads: ^0.11.0+4
  firebase_analytics: ^7.1.1
  firebase_performance: ^0.6.0

  ## https://github.com/PonnamKarthik/FlutterHtmlView
  #flutter_html_view: ^0.5.11
  flutter_widget_from_html_core: ^0.4.3
  launch_review: ^2.0.0

  # https://pub.dartlang.org/packages/fluttertoast
  fluttertoast: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_fonts: ^2.0.0

  # Your other dev_dependencies here
  build_runner: ^1.12.2
  json_serializable: ^4.1.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
   - assets/strings/version.txt
   - assets/strings/zh_tw.json
   - assets/drawable/
   - assets/drawable/2.0x/
   - assets/drawable/3.0x/
   - assets/licenses/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
