# flutter-action
# https://github.com/subosito/flutter-action
name: flutter-action

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'README.md'
    - '**.txt'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - 'README.md'
    - '**.txt'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.12.x' # you can use 1.12
        channel: 'stable' # or: 'dev' or 'beta'
    - run:
        dart --version
        flutter --version 
    - name: Build flutter apk
      run: 
        flutter pub get
        flutter build apk
#    - run: flutter test

